### ISSUE TITLE
Dropping Python 2 support.

### ISSUE THREAD

**Issue by ChinouneMehdi** [Goddard-Fortran-Ecosystem/pFUnit#131]
Isn't time to rise minimum supported Python to 3.5?
We are three months away from Python2.7 end of support.

**Comment by tclune** [comment]
It is certainly time to make certain that everything works with Python 3.x.     But I'm not in any rush to break things for Python 2.7.      Many users may not immediately update their environments just because 2.7 is no longer  technically supported.  E.g., several HPC systems used here at NASA have not yet changed the default from 2.6.

And I admit that I have been one of the bad players by continuing to use the default on my own workstation which is Python 2.7, and thus I'm oblivious when things break in Python 3.    I do plan Travis today to test with Python 3.x, which should cover things.
