### ISSUE TITLE
some tests failed in ubuntu 18 with gfortran

### ISSUE THREAD

**Issue by jdh13** [Goddard-Fortran-Ecosystem/pFUnit#142]
Hello,
i'm trying to install the files with git clone. My machine is Ubuntu 18.04 LTS, with gfortran 7.4.0.
Messages are:
```
85% tests passed, 2 tests failed out of 13

Total Test time (real) =   1.94 sec

The following tests FAILED:
	  3 - fhamcrest_tests (Failed)
	  6 - unit_test_processor (Failed)
Errors while running CTest
```

for 3, the error is related to:
`............At line 44 of file /home/me/src/pFUnit-Goddard/src/funit/fhamcrest/AnyOf.F90
Fortran runtime error: Index '1' of dimension 1 of array 'matchers%_data' above upper bound of 0
`

for 6, files are differents, see the attachment.

Am i right if i consider these errors not important?
Tanks in advance
![Screenshot from 2019-10-24 17-50-03](https://user-images.githubusercontent.com/822929/67503048-416a1580-f687-11e9-9b9b-98ba6edbabcc.png)

**Comment by tclune** [comment]
The 2nd failure is due to recent contributions to support python 3.x.    I independently ran into this issue and am pushing a fix once the CI tests run.  Hopefully tomorrow morning.

The fhamcrest failure is probably due to compiler limitations in gfortran.   You could either build without fhamcrest (-DSKIP_FHAMCREST=YES) or use a more recent gfortran compiler.   Or you can just live with the failures if you are not using hamcrest in your project.

**Comment by tclune** [comment]
Note the recent release should have resolved all such issues.  Please let me know if you are still seeing any problems with the self tests.
