### ISSUE TITLE
gfortran 9.2.0: allocatable polymorphic variable assignment not supported

### ISSUE THREAD

**Issue by jrwrigh** [Goddard-Fortran-Ecosystem/pFUnit#186]
I'm currently getting an error when attempting to build the program.

```bash
cd build
cmake ..
make tests
```
It eventually errors out on: 
```
/users/jrwrigh/.local/src/pFUnit/extern/fArgParse/src/BaseAction.F90:309.6:

      n_arguments = this%n_arguments
      1
Error: Assignment to an allocatable polymorphic variable at (1) is not yet supported
/users/jrwrigh/.local/src/pFUnit/extern/fArgParse/src/BaseAction.F90:110.9:
```

This would appear to be a `gcc` version issue, but the I can confirm that I am running `gcc 9.2.0`:

```
➜ gfortran --version
GNU Fortran (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Even explicitly setting the `gfortran` compiler in cmake isn't working:
```
cmake --CMAKE_FORTRAN_COMPILER=/usr/local/gcc/9.2.0/bin/gfortran ..
```

Any ideas what's happening?

**Comment by tclune** [comment]
This ones sounds very familiar.     I cannot reproduce on my mac with 👍 
```script
bash-3.2$ gfortran --version
GNU Fortran (Homebrew GCC 9.2.0_1) 9.2.0
...
```
Is it possible that there is a difference between 9.2.0_1 and 9.2.0 that was fixed?    I'll also try to investigate in Linux when I get a chance.

As a workaround, you could try replacing the offending line with:
```f90
allocate(n_arguments, source=this%n_arguments)
```
Why that sometimes helps Fortran compilers when it is all-but-equivalent is beyond me.

**Comment by rouson** [comment]
My guess is that the error message is misleadingly broad: `gfortran` has supported intrinsic assignment to polymorphic variables at least since version 8 and possibly before.  What might not have been supported until more recently was intrinsic assignment to _unlimited_ polymorphic variables, but even that seems to be supported in gfortran 9.2.0 for a simple case. gfortran 9.2.0 (Homebrew GCC 9.2.0_3) compiles the following cleanly:
```fortran
program main
  implicit none

  type foo
    integer :: i=1
  end type

  class(*), allocatable :: n_arguments

  type(foo) :: bar

  n_arguments = bar%i

end program
```
but the above code generates an internal compiler error with gfortran 8.3.0, suggesting that support for this feature is very recent.  The `gfortran` developers are officially in the bug-fixing phase of development until the upcoming GCC 10 release so this is a good time to submit bug reports.  I suspect your case is a bug rather than a missing feature.

**Comment by tclune** [comment]
I definitely agree that the message it potentially misleading.    Analogous constructs are used throughout my code and do work under 9.2.    This particular case must bring in some other aspect, though I have no idea as to what.

**Comment by tclune** [comment]
Unfortunately, I am unable to reproduce the issue on our linux cluster as well.    One thought:   was this a fresh clone/install of pFUnit?     I'm wondering if your build has access to an older version of fArgParse and is therefore not building a fresh version of that layer.    I know that's a long shot, but I don't have any other thoughts, and this has explained some user's issues in the past.

**Comment by jrwrigh** [comment]
This was a brand new install of pFUnit. I don't believe anyone else in my group has used any of the other Goddard utilities either.

**Comment by jrwrigh** [comment]
I just tested with the example program that @rouson [commented](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/issues/186#issuecomment-577744428), and that compiles and runs without error. I have a feeling that `cmake` may be grabbing the wrong fortran compiler. Is there a way to specify the fortran compiler path?

**Comment by jrwrigh** [comment]
Success! `cmake` was finding the wrong compiler. Things to note for future users:

1) When running cmake initially, it will say which compiler it is using and even what version it is:

```
➜ cmake ..                                                                                                             
-- The Fortran compiler identification is GNU 4.9.2
-- The C compiler identification is GNU 4.9.2
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
....
```
2) To explicitly set the fortran compiler path, use the flag `-DCMAKE_Fortran_COMPILER=<path-to-compiler>`

**Comment by jrwrigh** [comment]
I guess the only suggestion as a "fix" would be to have `cmake` search the `$PATH` for the compiler instead of going straight to `/usr/bin*`.

**Comment by tclune** [comment]
I at the very least could probably create a more useful FAQ for troubleshooting.   There are unfortunately many ways of setting the compiler, and I tend to forget the recommended method as I have one that works for me ... 

You're not the first user that was unintentionally using the system default compiler, but it seems in the past the errors were more obviously due to a very old compiler.   The error you saw was too plausibly in the "barely works" category of modern compilers.

Glad it is resolved.
