### ISSUE TITLE
Windows Subsystem for Linux issue

### ISSUE THREAD

**Issue by tclune** [Goddard-Fortran-Ecosystem/pFUnit#227]
From: 
https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos/issues/7

GFortran 9 under WSL fails with the default optimizations.   A check is needed to change optimizations for this configuration.

**Comment by ChinouneMehdi** [comment]
The failure was because of https://github.com/microsoft/WSL/issues/3083
the "https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/main/include/driver.F90" program contains an internal function which is equivalent to a nested function in C.
The failure disappear with higher optimization because the compiler inline the internal function.
a proper fix is to but the internel function "load_tests" in a module.
I can push a PR if it is OK.
