### ISSUE TITLE
pFUnit without MPI

### ISSUE THREAD

**Issue by kurtsansom** [Goddard-Fortran-Ecosystem/pFUnit#245]
Are there instructions on using pFUnit without MPI? It seems to be a hard requirement?

**Comment by tclune** [comment]
Definitely not a hard requirement.    No doubt the instructions could be improved.

There are a couple of facets to your question.   First, it is possible to not even compile the MPI support.   By default cmake build will  attempt to discover if there is an MPI compiler in your environment (using cmake's `find_package()`) and if so it will build the MPI layers.   If not, it will skip those.   If you want to skip the MPI layers regardless you can use `-DMPI=NO` on the cmake configuration step to force the issue.

But even if you have built and installed pFUnit with the MPI layer you do not need to use that layer in your own applications.   (This was different in pFUnit 3.x and earlier where you either used MPI throughout or not.)       For serial tests you should have `use FUnit` instead of `use pFUnit`.    And then you should link in -lfunit and not -lpfunit.    There are other dependencies that also must be linked, but this is the only different for an MPI vs non-MPI executable.

**Comment by tclune** [comment]
I belatedly realized I should have pointed you at the demos repo: https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos

In there you will find simple examples for building and running serial tests.     Examples include build scripts with make and with cmake.

**Comment by kurtsansom** [comment]
where would be a good place to put that documentation?

**Comment by tclune** [comment]
Either the relevant section in the README.md file in the top directory.   Or with a bit more ambition we could look at starting to use the Wiki.    The original documentation in the ./documentation folder got stale and was difficult to maintain.   The existing README was a quick-and-dirty attempt to highlight the main things users need.

Unfortunately, on any given day writing documentation does not bubble up to a priority.      I'm happier to create more expansive (and relevant) examples under the demo repository - but that's not sufficient for all purposes.

Let me know if you'd like to add something to the Wiki - happy to add you as a collaborator.

**Comment by kurtsansom** [comment]
is the file extension `.pf` required? it doesn't appear to be but it was not immediately clear.

**Comment by tclune** [comment]
No - it should not be.    Early on the preprocessor was a bit more rigid, but it should not be an issue now.    If you don't use cmake for your application you probably want to have a convention and a rule for what suffix you prefer.    I recommend against `.F90` though as the code is not legal Fortran until it is processed.   (And you don't have to use the preprocessor - it just really simplifies some of the otherwise tedious aspects of using the framework.)

To be fair, I've not used anything other than `.pf` in some time, so let me know if you encounter a problem with a different suffix.
