### ISSUE TITLE
Difference between `@mpiAssert*` and `@assert*` directives?

### ISSUE THREAD

**Issue by ZedThree** [Goddard-Fortran-Ecosystem/pFUnit#269]
Is there a difference between the `@mpiAssert*` directives and the plain `@assert` versions? Practically, it seems that the `@mpiAssert` versions don't generate a `if (anyExceptions()) return`, but I'm not sure why that would be important for MPI.

**Comment by tclune** [comment]
These specialized asserts are needed to avoid deadlocks in situations where there is a branch in the test code.    This is because  `anyExceptions()` has a call to `MPI_Gather()` under the hood.

 I find these situations rare, as most tests are for serial components, and most remaining tests of parallel components don't need such branches.     As a concrete example, suppose you have a unit test where the rank-0 logic is different than for other ranks:

```
if (this%getProcessRank() == 0) then
    @assert(...)
end if
```
If you use the regular assert as above, and the the root process experiences one more `anyExceptions()` than the other ranks and thus causes a deadlock even if there were no actual failures.    

But one must also be careful even when using `@mpiAssert`:

```
if (this%getProcessRank() == 0) then
    @mpiAssert(...)
end if
...
@assert(...)
```
If the first `@mpiAssert` fails, then the other processes will hang at the gather in the later `@assert`.

If you are familiar with MPI and parallel processing, it is usually straightforward what to do in any given situation.   But of course, best of all if you can avoid such branching in the test in the first place.

**Comment by ZedThree** [comment]
Thanks!

This comment would be really good to put in the documentation, although it seems to have gotten a bit fragmented since v3. It would be nice to have some automatically built documentation hosted somewhere. I've recently setup both readthedocs and FORD for various projects, so I would be happy to contribute some effort towards one of those if you were interested.

**Comment by tclune** [comment]
Up to date documentation would definitely be  a good idea.      Just very hard for me to ever get it to a top priority.      I'm fine with FORD.   For my day-job, I've had to compromise on Doxygen as it aligns with other org activities.      

Contributions in this direction more than welcome.
