### ISSUE TITLE
useful way to test "error stop"

### ISSUE THREAD

**Issue by kurtsansom** [Goddard-Fortran-Ecosystem/pFUnit#296]
with pFUnit Is there a useful way to test when "error stop" is thrown?

**Comment by kurtsansom** [comment]
Thank you so much for the reply @tclune 

I think I was originally shooting for the first half, and I am glad I didn't go down that path to far. 

The second aspect you mention makes the most sense, but it sounds like it would not be worth the additional effort in the short term for testing one exception?

At what point would it make more sense to use one of the exceptions libraries out there for fortran and remove calls to `error stop`?

The other thought along the lines of exception handling is that it looks like pfunit has exception handling built in, therefore one could use that as the basis for handling exceptions that would also be testable (remove `error stop`). My hesitation here is using the same framework for exceptions and testing and could cause a conundrum later, but I guess it would be relatively low risk depending on the application.

**Comment by MuellerSeb** [comment]
Could we reopen this? I am interested in the code that @tclune mentioned here:
> If the latter case is what you are asking about, I can point you to some code that works in the manner that I've described.

We are looking for a good way to check routines for correctly throwing errors.

**Comment by tclune** [comment]
I did spend a bit of time this weekend looking at what could be done here.   As I've said before, the robust runner will at least (in theory) let test suites run in the presence of things that stop execution (including ERROR STOP), but there is currently no way to indicate that this is expected.

I think we could add a new annotation like `@STOPS` that would indicate the robust runner to expect the failure and then "forgive" the failure and make it a success.  (And if the test runs successfully, it would throw an exception that a stop was expected.)

It's not the easiest bits of code to work with, but I can make a concerted stab at it next weekend.     

My long term recommendation remains to introduce run-time flexibility so that under testing these "stops" become some form of exception and instead return, but I understand that this is not necessarily easy for a large/deep calling tree.
