### ISSUE TITLE
proper use of @disable

### ISSUE THREAD

**Issue by kurtsansom** [Goddard-Fortran-Ecosystem/pFUnit#301]
is the syntax:
```
     @test
     @disable
``` 
required to disable a a test? previously I was using `@disable` by itself, which didn't raise any issues (fails silently?) in a module with several `@tests`. When `@disable` is used at the first subroutine in a module the pFUnitParser fails because the `current_method` attribute is missing.

**Comment by kurtsansom** [comment]
After investigating I realized using `@disable` by itself is essentially ignored.
```
     @test
     @disable
```
is required.

**Comment by tclune** [comment]
I honestly don't recall whether `@disable` ever worked on its own, though clearly that would be good.   Quite possibly some other change in the preprocessor broke this.    Will try to investigate this weekend.

**Comment by tclune** [comment]
I'm inclined to leave the functionality as-is, because it is in line with the JUnit annotations on which it is modeled.

Of course, JUnit has moved from `@disable` to `@ignore`, so I should really get around to adding an alias for that annotation and mark the other one as deprecated.   OTOH, I'm unlikely to keep trying to "keep up" with JUnit - just too many things that are comparably harder to do in Fortran.

**Comment by kurtsansom** [comment]
It makes sense to me now, I didn't have the right mental model at first.
