### ISSUE TITLE
CMake/CTest Integration?

### ISSUE THREAD

**Issue by citibeth** [Goddard-Fortran-Ecosystem/pFUnit#39]
Does pFUnit have integration with CMake that allows the tests to run as part of the build?  Something like this for GTest:

https://cmake.org/cmake/help/v3.10/module/GoogleTest.html

**Comment by tclune** [comment]
I believe there is some code in the release version that was contributed by users.    My projects were generally mature before it was provided (and before I'd become proficient with cmake), so I have not used it much.

There is a file ./cmake/PreprocessMacro.cmake  that does part of what you are looking for.

In my more recent projects I'm using something like that macro combined with CMake's ctest.   I have a separate test executable in each test directory.   I then use CMake add_test() to define a test and add it to the dependencies of a global target "tests" that is defined in the top-level:

   add_custom_target(tests COMMAND ${CMAKE_CTEST_COMMAND})

Then "make tests" will build and run my tests.    And one can also use "ctest", but that won't actually update the tests.   And because CMAKE_TEST_COMMAND eats the output, when the tests fail you'll need to manually run with "ctest -V" to see the pFUnit detailed diagnoses.

Hope this helps.

**Comment by ZedThree** [comment]
I used the following and it seemed to work pretty well:

```cmake
find_package(pFUnit)
if(PFUNIT_FOUND)
  include(CTest)
  enable_testing()
  set(TEST_SOURCES
    tests/test_binary_tree.pf
    tests/test_redblack_tree.pf
    )
  add_pfunit_test(rb_tests "${TEST_SOURCES}" "" "")
  target_link_libraries(rb_tests rbtree)
endif()
```

**Comment by tclune** [comment]
I am glad to hear this is working for you.   The code was contributed by another user, and I've not been using it in my own projects (yet).    4.0 is getting close and I will definitely me migrating my projects to use this approach.     One wrinkle that might change this slightly is that 4.0 will allow the driver to use a file name other than testSuites.inc to be loaded.    I think/hope I can leave that as an optional argument in the above so that existing code does not break.
