### ISSUE TITLE
Need @assertAlmostEqual()

### ISSUE THREAD

**Issue by citibeth** [Goddard-Fortran-Ecosystem/pFUnit#42]
...like in Python

https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual

**Comment by tclune** [comment]
Sorry - this ticket was poorly timed.   I'd just gone on vacation before the furlough and did not look at the right window of time when I scanned the open tickets later on.

pFUnit has what you are looking for.      We just did not give it a different name.  AssertEqual() for reals, has an optional argument "tolerance", that is 0 by default (exact equality).

Note there is also @assertRelativelyEqual which interprets the tolerance as a relative error rather than an absolute error.
