### ISSUE TITLE
Roadmap for 4.0

### ISSUE THREAD

**Issue by d7919** [Goddard-Fortran-Ecosystem/pFUnit#69]
We're looking at adopting pFUnit for unit testing in a fairly large project but before working on this integration just wanted to check if there is an expected timescale for moving from 3 to 4 and what level of backwards compatibility can we anticipate? It would be good to see if there are places we might be able to contribute.

Is there a public roadmap for the next major version of pFUnit?

**Comment by tclune** [comment]
The good news is that I was able to spend considerable time in January on developing 4.0.   (One of the few things I could spend time on during the US gov't shutdown.)   I think I can commit to a release by April 1, but I hope to get it out in the next 1-2 weeks now.

I've not yet tried to port an existing project to use the develop version.   But to my current knowledge these are the backward compatibility issues:

### Backward compatibility issues:

- 4.0 requires some F2008 support.  I've been developing with ifort 18.0.3, gfortran 8.2, and nag 6.2.   Slightly older versions might work, but I would not bet on it.
- "use pFUnit_mod" becomes "use pFUnit" or "use FUnit" depending on whether the file is parallel or serial.  (If you build with MPI then "USE PFUNIT" is always fine.)     If people complain I can add a wrapper module to allow the "_MOD" suffix. 
- The link step is slightly different.   Previously the link was "-lpfunit".  Now, instead of separate builds of pFUnit for serial and parallel, 4.0 can produce two libraries in one build.   Serial applications link with "-lfunit" and parallel applications link with "-lpfunit -lfunit".   (Note - building the parallel library is optional.)
- The output format of some assertions may have changed slightly
- Build support is now strictly via CMake.   
-- If users want a more traditional build with make, they can contribute and maintain it.


### Roadmap?
Regarding a roadmap ...  I am not terribly organized and merely have a few threads where I've stated my goals for 4.0 capabilities.   Hopefully I've been mostly consistent.     Some new things will only have basic capabilities completed and will provide an excellent opportunity for further contributions.    Here I'll summarize the new capabilities and and hint at contribution opportunities:

### New features in 4.0

- General cleanup of code
-- Cleaner delineation between the core and extensions (e.g. MPI is now an extension directory)
-- Consistent naming conventions
-- Consistent use of deferred-length strings
-- Dropping CamelCase in favor of snake_case for variables and methods.   (Not 100% complete, but is only internal anyway.   Class names remain CamelCase, and externally used methods will have generics for backward compatibility.)
-- Cleaner templates for overloading asserts
-- Top level driver is now very streamlined
- Eliminated legacy Makefiles
- New and (hopefully) improved implementation of RobustRunner for tests that crash or hang.
- Support for hamcrest (I am very excited about this)
-- hamcrest combined with MPI is tantalizing, but needs further thought and will probably not be available until 4.1
-- Many opportunities for user-contributions here
- Support for Test Anything Protocol (TAP)
- Extensible support for new annotations
-- E.g., There is now an @disable annotation that skips a given test (and mentions that in the summary)
-- Some opportunities for user contributions here
- Basic extensions to the core
-- MPI support is now an extension of the core
-- ESMF support 
-- Hoping for user contributions for coarrays using F2018 team features
- Improved support for command-line arguments (analogous to python argParse)
- Can specify on command line a filter which only runs tests that match a simple naming pattern
-- Currently this is an exact substring match
-- Should expand capability to allow wildcards and maybe regexp

**Comment by tclune** [comment]
Once I release 4.0, I'll start a GitHub "project" for the 4.1 release.   This should allow coordination with those interested in making specific contributions.

**Comment by d7919** [comment]
Thanks for the very detailed response, this is really helpful.
